# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [14]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 4], [2, 5], [2, 3]])
C = np.array([[52, 43], [12, 51], [27, 73]])
# Your code here
print(A.T.dot(B+C))
print(A.T.dot(B) + A.T.dot(C))

assert((A==A).all())#np.equal(A, A))
assert((A.T.dot(B+C) == A.T.dot(B) + A.T.dot(C)).all())

[[240 595]
 [336 774]]
[[240 595]
 [336 774]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [15]:
# Your code here 
A = np.array([[1, 2, 3], [3, 4, 7], [5, 6, 9]])
B = np.array([[1, 12, 3], [3, 14, 7], [5, 16, 9]])
C = np.array([[1, 21, 3], [13, 41, 17], [51, 61, 91]])
print((A.dot(B)).dot(C))
print(A.dot((B.dot(C))))
assert(((A.dot(B)).dot(C) ==A.dot((B.dot(C)))).all())

[[ 3410  6754  5566]
 [ 7802 15514 12718]
 [10850 21654 17658]]
[[ 3410  6754  5566]
 [ 7802 15514 12718]
 [10850 21654 17658]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [21]:
# Your code here 
m1 = A.dot(B)
m2 = B.dot(A)
print(m1,'\n\n', m2)

assert((m1 != m2).all())


[[ 22  88  44]
 [ 50 204 100]
 [ 68 288 138]] 

 [[ 52  68 114]
 [ 80 104 170]
 [ 98 128 208]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [22]:
# Your code here 
x = np.array([1,2,3,4,5,])
y = np.array([12,13,4,17,22])
s1 = x.T.dot(y)
s2 = y.T.dot(x)
print(s1, s2)
assert(s1==s2)

228 228


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [26]:
# Your code here 
l = (A.dot(B)).T
r = (B.T).dot((A.T))
print(l,'\n', r)
assert((l==r).all())

[[ 22  50  68]
 [ 88 204 288]
 [ 44 100 138]] 
 [[ 22  50  68]
 [ 88 204 288]
 [ 44 100 138]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 